### ISSUE TITLE
Foreman server needs reverse lookup to be trusted by foreman_proxy

### ISSUE THREAD

**Issue by beddari** [norcams/himlar#104]
In order to limit which hosts (that have a Puppet cert and) can talk to foreman_proxy there is a trusted_hosts setting in the foreman_proxy module. In order for this to work we need to have the Foreman server registered in reverse DNS.

https://github.com/theforeman/puppet-foreman_proxy/blob/master/templates/settings.yml.erb#L30-L36

```
no name for 129.240.224.101
129.240.224.101 - - [30/Mar/2015 15:31:21] "GET /features HTTP/1.1" 403 161 0.0017
E, [2015-03-30T16:12:39.990821 #27691] ERROR -- : Unable to resolve hostname for connecting client - 129.240.224.101. If it's to be a trusted host, ensure it has a reverse DNS entry.
```

**Comment by mikaeld66** [comment]
Har lagt inn for Oslo nå (manuelt)
