### ISSUE TITLE
firewall rules break bootstrap run on master

### ISSUE THREAD

**Issue by beddari** [norcams/himlar#179]
The "020 allow all from transport" firewall rule on the master role breaks bootstrap runs of Puppet.

We need to rework how/if we try iptables management during bootstrap.

**Comment by TorLdre** [comment]
This is not true anymore, after

https://github.com/norcams/himlar/commit/5aac384c1f5f91bd137c9fafc4880ab7ee912e25

which loads dummy module. After that, no empty IP address was returned to code.

**Comment by TorLdre** [comment]
Issue #173 will fix the error messages anyway.
