### ISSUE TITLE
Update the network puppet module

### ISSUE THREAD

**Issue by TorLdre** [norcams/himlar#214]
Our project uses a private fork of example42/puppet-network with a change that won't be accepted by upstream. We need new functionality from upstream for creation of routes, for example for osl-foreman (in order to reach oob interfaces).

**Comment by TorLdre** [comment]
It would enable us to write /etc/sysconfig/network-scripts/route-eth0:
172.17.32.0/21 via 172.16.32.1 dev eth0

**Comment by beddari** [comment]
Depending on the urgency of this I'll see if I can redo https://github.com/example42/puppet-network/pull/84 with a backwards compatible change so that we can get a version of the change upstream.

Ref https://github.com/beddari/puppet-network/commit/3aa66859b7108ea7356cc5a48952be9ee89dd5af

**Comment by TorLdre** [comment]
That would really be something.

**Comment by TorLdre** [comment]
Fixed.
