### ISSUE TITLE
ipmitool power control not working

### ISSUE THREAD

**Issue by beddari** [norcams/himlar#51]
foreman-proxy for some reason fails sending power control commands to our 13G servers. Needs investigation.

**Comment by TorLdre** [comment]
This problem can be solved (or, rather a nasty workaround) by editing
/usr/share/gems/gems/rubyipmi-0.8.1/lib/rubyipmi/ipmitool/connection.rb

and replace the line
@options['I'] = .... with
@options['I'] = 'lanplus'

Foreman-proxy can then use the ipmitool bmc provider to control the Dell idrac on 13g servers.

**Comment by johnrothermel** [comment]
This was very helpful in my 1.8 foreman release. It also appears that rubyipmi 0.10 driver map will default to lan20 or lanplus so foreman 1.9 shouldn't have this issue.

**Comment by hassaan-xflow** [comment]
do I need to do anything else after editing the file?

**Comment by TorLdre** [comment]
hassaan-xflow: Check your /etc/foreman-proxy/bmc.yaml to read

:bmc_default_provider: ipmitool

and that ipmitool is installed.

**Comment by TorLdre** [comment]
This now works in out of the box foreman (tested in 1.10, may have been fixed before that).
